### ISSUE TITLE
Buscar elementos en la matriz

### ISSUE THREAD

**Issue by Jorge85015** [mmasias/unLaberinto#1]
Hola Manuel, tengo una duda, cómo podría buscar la matriz si aún quedan elementos iguales a cierto número? para que, si ya no queda ningun elemento 0 (por ejemplo), entonces haga algo,

gracias, saludos

**Comment by mmasias** [comment]
@Jorge85015 La diapo 15 de la presentación **_P1 - S01E10 - Variables II - Arreglos (Parte 2)_** te puede dar ciertas pistas: la tienes en el campus. De todos modos, básicamente es recorrerlo comparando elemento a elemento y activar una bandera a la primera que encuentres el valor 0. 

¡Ánimo!
